version: '3'

services:
  bot:
    build:
        context: ..
        dockerfile: ./compose/dev/bot/Dockerfile
    restart: always
    command: ./start.sh
    env_file:
      - ../env/.env.app
    depends_on:
      - db
  db:
    image: postgres:alpine
    restart: always
    env_file:
      - ../env/.env.pg
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
